In [1]:
import numpy as np

In [13]:
b1 = [6.59, 7.16, 5.07, 6.75]
b2 = [6.59, 7.59, 4.96, 6.62]

In [14]:
box1 = [b1[0] - b1[2] / 2, b1[1] - b1[3] / 2, b1[0] + b1[2] / 2, b1[1] + b1[3] / 2]
box2 = [b2[0] - b2[2] / 2, b2[1] - b2[3] / 2, b2[0] + b2[2] / 2, b2[1] + b2[3] / 2]

In [15]:
box1

[4.055, 3.785, 9.125, 10.535]

In [16]:
box2

[4.109999999999999, 4.279999999999999, 9.07, 10.9]

In [17]:
for i in range(4):
    box1 = np.expand_dims(box1, axis=0)
    box2 = np.expand_dims(box2, axis=0)

In [19]:
lu = np.maximum(box1[:, :, :, :, 0:2], box2[:, :, :, :, 0:2])
rd = np.minimum(box1[:, :, :, :, 2:],  box2[:, :, :, :, 2:])

In [20]:
lu

array([[[[[ 4.11,  4.28]]]]])

In [21]:
rd

array([[[[[  9.07 ,  10.535]]]]])

In [22]:
intersection = rd - lu 

In [31]:
inter_square = intersection[:, :, :, :, 0] * intersection[:, :, :, :, 1]

In [32]:
mask = (intersection[:, :, :, :, 0] > 0).astype(float) * (intersection[:, :, :, :, 1] > 0).astype(float)

In [33]:
inter_square = mask * inter_square

In [34]:
square1 = (box1[:, :, :, :, 2] - box1[:, :, :, :, 0]) * (box1[:, :, :, :, 3] - box1[:, :, :, :, 1])

In [35]:
square2 = (box2[:, :, :, :, 2] - box2[:, :, :, :, 0]) * (box2[:, :, :, :, 3] - box2[:, :, :, :, 1])

In [36]:
inter_square / (square1 + square2 - inter_square + 1e-6)

array([[[[ 0.86101311]]]])